# -*- coding: utf-8 -*-
"""Task 01_Caesar Ciphar Algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giEcVs57c43Lrgm9oBDvwHReG21U8CuK
"""

def encrypt(text, shift):
    result = ""

    for char in text:
        if char.isalpha():
            shift_base = 65 if char.isupper() else 97
            result += chr((ord(char) - shift_base + shift) % 26 + shift_base)
        else:
            result += char

    return result


def decrypt(text, shift):
    return encrypt(text, -shift)


def main():
    print("\nCaesar Cipher Tool")

    while True:
        print("\n1. Encrypt")
        print("2. Decrypt")
        print("3. Exit")

        choice = input("Choose option (1/2/3): ")

        if choice == "3":
            print("Exiting program...")
            break

        message = input("Enter your message: ")
        shift = int(input("Enter shift value: "))

        if choice == "1":
            print("Encrypted:", encrypt(message, shift))
        elif choice == "2":
            print("Decrypted:", decrypt(message, shift))
        else:
            print("Invalid choice! Try again.")


if __name__ == "__main__":
    main()